### ISSUE TITLE
Not currently rendering on Firefox

### ISSUE THREAD

**Issue by hughsk** [openmaptiles/positron-gl-style#13]
Browser: Firefox 61.0.1
OS: Windows 10 Home, 1803

Also applies to the majority of other GL styles — can quickly test/verify by checking the [styles page](https://openmaptiles.org/styles/) on the website. Yields the following errors/warnings in the console:

![2018-07-26 16_26_11-](https://user-images.githubusercontent.com/569817/43268495-baee9968-90e8-11e8-8f18-5b36e6868a88.png)
![2018-07-26 16_29_11-](https://user-images.githubusercontent.com/569817/43268496-bb0a95aa-90e8-11e8-9559-e664bbb14f17.png)

I've also been getting the same error running a map locally on Firefox/Windows:

![2018-07-26 16_32_39-](https://user-images.githubusercontent.com/569817/43268730-45c5557c-90e9-11e8-8657-58bcbc0d3981.png)

The same project setup was working three or four weeks ago, so perhaps a change in the styles or Firefox's CORS policies has caused some issues? It still works great in Chrome.

Thanks! :)

**Comment by klokan** [comment]
Problem not reproduced.

The maps run fine with latest Firefox - Quantum v61.0.1 on Mac OS X.

![screen shot 2018-07-31 at 15 18 09](https://user-images.githubusercontent.com/59284/43462100-7e94c992-94d5-11e8-9c56-ab825a690286.png)

- Don't you have some malicious plugin/extension in Firefox which is causing this?

**Comment by hughsk** [comment]
Ah you're right! This was because of [Privacy Badger](https://www.eff.org/privacybadger), which blocked it after a while because the tile/style server was using cookies. Sorry for the trouble and thanks very much for your help :)

**Comment by hughsk** [comment]
Update: getting 403s for all of your `gh-pages` hosted styles now, including using `https://openmaptiles.github.io/osm-bright-gl-style/style-cdn.json` as [listed in your documentation](https://openmaptiles.org/docs/website/mapbox-gl-js/). Happens in Chrome, Firefox, and with `curl`.

Just getting "Origin not allowed". Not clear if this is intentional or not? Am only using them only `http://localhost:9966`.
