### ISSUE TITLE
The demo map doesn't work

### ISSUE THREAD

**Issue by memarv** [openmaptiles/positron-gl-style#17]
https://openmaptiles.github.io/positron-gl-style
In the console I see an error:
"Access to fetch at 'https://maps.tilehosting.com/data/v3.json?key=SymbVzXrAD6Jmqe6yBOS' from origin 'https://openmaptiles.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

**Comment by TomPohys** [comment]
Fixed in https://github.com/openmaptiles/positron-gl-style/commit/98f91afa38671a885947d721075bdc88392c1b78.
